<?php

namespace Database\Seeders;
use App\Models\User;
use App\Models\Utility;
use Illuminate\Support\Facades\Hash;
use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;

class UsersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $arrPermissions = [
            [
                'name' => 'show dashboard',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'manage user',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'create user',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'edit user',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'delete user',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'create language',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'manage system settings',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'manage role',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'create role',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'edit role',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'delete role',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'manage permission',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'create permission',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'edit permission',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'delete permission',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'manage company settings',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'manage business settings',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'manage stripe settings',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'manage expense',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'create expense',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'edit expense',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'delete expense',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'manage invoice',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'create invoice',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'edit invoice',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'delete invoice',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'show invoice',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'create payment invoice',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'delete payment invoice',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'send invoice',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'delete invoice product',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'convert invoice',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'manage plan',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'create plan',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'edit plan',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'manage constant unit',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'create constant unit',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'edit constant unit',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'delete constant unit',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'manage constant tax',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'create constant tax',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'edit constant tax',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'delete constant tax',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'manage constant category',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'create constant category',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'edit constant category',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'delete constant category',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'manage product & service',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'create product & service',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'edit product & service',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'delete product & service',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'manage customer',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'create customer',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'edit customer',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'delete customer',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'show customer',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'manage vender',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'create vender',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'edit vender',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'delete vender',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'show vender',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'manage bank account',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'create bank account',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'edit bank account',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'delete bank account',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'manage transfer',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'create transfer',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'edit transfer',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'delete transfer',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'manage constant payment method',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'create constant payment method',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'edit constant payment method',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'delete constant payment method',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'manage transaction',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'manage revenue',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'create revenue',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'edit revenue',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'delete revenue',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'manage bill',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'create bill',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'edit bill',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'delete bill',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'show bill',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'manage payment',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'create payment',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'edit payment',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'delete payment',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'delete bill product',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'buy plan',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'send bill',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'create payment bill',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'delete payment bill',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'manage order',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'income report',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'expense report',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'income vs expense report',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'invoice report',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'bill report',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'stock report',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'tax report',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'loss & profit report',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'manage customer payment',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'manage customer transaction',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'manage customer invoice',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'vender manage bill',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'manage vender bill',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'manage vender payment',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'manage vender transaction',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'manage credit note',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'create credit note',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'edit credit note',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'delete credit note',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'manage debit note',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'create debit note',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'edit debit note',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'delete debit note',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'duplicate invoice',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'duplicate bill',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'manage coupon',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'create coupon',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'edit coupon',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'delete coupon',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'manage proposal',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'create proposal',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'edit proposal',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'delete proposal',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'duplicate proposal',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'show proposal',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'send proposal',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'delete proposal product',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'manage customer proposal',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'manage goal',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'create goal',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'edit goal',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'delete goal',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'manage assets',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'create assets',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'edit assets',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'delete assets',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'statement report',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'manage constant custom field',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'create constant custom field',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'edit constant custom field',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'delete constant custom field',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'manage chart of account',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'create chart of account',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'edit chart of account',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'delete chart of account',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'manage journal entry',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'create journal entry',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'edit journal entry',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'delete journal entry',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'show journal entry',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'balance sheet report',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'ledger report',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'trial balance report',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'create budget planner',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'edit budget planner',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'manage budget planner',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'delete budget planner',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'view budget planner',
                'guard_name' => 'web',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'name' => 'manage contract',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'create contract',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'manage customer contract',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'edit contract',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'delete contract',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'view contract',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'duplicate contract',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'delete attachment',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'delete comment',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'delete notes',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'contract description',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'upload attachment',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'add comment',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'add notes',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'send contract mail',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            [
                'name' => 'manage retainer',
                'guard_name' => 'web',
                'created_at' => date('Y - m - d H:i:s'),
                'updated_at' => date('Y - m - d H:i:s'),
            ],
            
            
            
            
            
            
        ];

        Permission::insert($arrPermissions);

        // Super admin

        $superAdminRole        = Role::create(
            [
                'name' => 'super admin',
                'created_by' => 0,
            ]
        );
        $superAdminPermissions = [
            ['name' => 'manage user'],
            ['name' => 'create user'],
            ['name' => 'edit user'],
            ['name' => 'delete user'],
            ['name' => 'create language'],
            ['name' => 'manage system settings'],
            ['name' => 'manage stripe settings'],
            ['name' => 'manage role'],
            ['name' => 'create role'],
            ['name' => 'edit role'],
            ['name' => 'delete role'],
            ['name' => 'manage permission'],
            ['name' => 'create permission'],
            ['name' => 'edit permission'],
            ['name' => 'delete permission'],
            ['name' => 'manage plan'],
            ['name' => 'create plan'],
            ['name' => 'edit plan'],
            ['name' => 'manage order'],
            ['name' => 'manage coupon'],
            ['name' => 'create coupon'],
            ['name' => 'edit coupon'],
            ['name' => 'delete coupon'],
        ];
        $superAdminRole->givePermissionTo($superAdminPermissions);

        $superAdmin = User::create(
            [
                'name' => 'Super Admin',
                'email' => 'superadmin@example.com',
                'password' => Hash::make('1234'),
                'type' => 'super admin',
                'lang' => 'en',
                'avatar' => '',
                'created_by' => 0,
            ]
        );
        $superAdmin->assignRole($superAdminRole);

        // customer
        $customerRole       = Role::create(
            [
                'name' => 'customer',
                'created_by' => 0,
            ]
        );
        $customerPermission = [
            ['name' => 'manage customer payment'],
            ['name' => 'manage customer transaction'],
            ['name' => 'manage customer invoice'],
            ['name' => 'show invoice'],
            ['name' => 'show proposal'],
            ['name' => 'manage customer proposal'],
            ['name' => 'show customer'],
            ['name' => 'manage customer contract'],
            ['name' => 'view contract'],
            ['name' => 'contract description'],
            ['name' => 'upload attachment'],
            ['name' => 'add comment'],
            ['name' => 'add notes'],

            
            

            
        ];

        $customerRole->givePermissionTo($customerPermission);

        // vender
        $venderRole       = Role::create(
            [
                'name' => 'vender',
                'created_by' => 0,
            ]
        );
        $venderPermission = [
            ['name' => 'vender manage bill'],
            ['name' => 'manage vender bill'],
            ['name' => 'manage vender payment'],
            ['name' => 'manage vender transaction'],
            ['name' => 'show vender'],
            ['name' => 'show bill'],
        ];

        $venderRole->givePermissionTo($venderPermission);

        // company
        $companyRole        = Role::create(
            [
                'name' => 'company',
                'created_by' => $superAdmin->id,
            ]
        );
        $companyPermissions = [
            ['name' => 'show dashboard'],
            ['name' => 'manage user'],
            ['name' => 'create user'],
            ['name' => 'edit user'],
            ['name' => 'delete user'],
            ['name' => 'manage role'],
            ['name' => 'create role'],
            ['name' => 'edit role'],
            ['name' => 'delete role'],
            ['name' => 'manage permission'],
            ['name' => 'create permission'],
            ['name' => 'edit permission'],
            ['name' => 'delete permission'],
            ['name' => 'manage company settings'],
            ['name' => 'manage business settings'],
            ['name' => 'manage expense'],
            ['name' => 'create expense'],
            ['name' => 'edit expense'],
            ['name' => 'delete expense'],
            ['name' => 'manage invoice'],
            ['name' => 'create invoice'],
            ['name' => 'edit invoice'],
            ['name' => 'delete invoice'],
            ['name' => 'show invoice'],
            ['name' => 'manage plan'],
            ['name' => 'buy plan'],
            ['name' => 'manage product & service'],
            ['name' => 'create product & service'],
            ['name' => 'delete product & service'],
            ['name' => 'edit product & service'],
            ['name' => 'manage constant tax'],
            ['name' => 'create constant tax'],
            ['name' => 'edit constant tax'],
            ['name' => 'delete constant tax'],
            ['name' => 'manage constant category'],
            ['name' => 'create constant category'],
            ['name' => 'edit constant category'],
            ['name' => 'delete constant category'],
            ['name' => 'manage constant unit'],
            ['name' => 'create constant unit'],
            ['name' => 'edit constant unit'],
            ['name' => 'delete constant unit'],
            ['name' => 'manage customer'],
            ['name' => 'create customer'],
            ['name' => 'edit customer'],
            ['name' => 'delete customer'],
            ['name' => 'show customer'],
            ['name' => 'manage vender'],
            ['name' => 'create vender'],
            ['name' => 'edit vender'],
            ['name' => 'delete vender'],
            ['name' => 'show vender'],
            ['name' => 'manage bank account'],
            ['name' => 'create bank account'],
            ['name' => 'edit bank account'],
            ['name' => 'delete bank account'],
            ['name' => 'manage transfer'],
            ['name' => 'create transfer'],
            ['name' => 'edit transfer'],
            ['name' => 'delete transfer'],
            ['name' => 'manage revenue'],
            ['name' => 'create revenue'],
            ['name' => 'edit revenue'],
            ['name' => 'delete revenue'],
            ['name' => 'manage bill'],
            ['name' => 'create bill'],
            ['name' => 'edit bill'],
            ['name' => 'delete bill'],
            ['name' => 'show bill'],
            ['name' => 'manage payment'],
            ['name' => 'create payment'],
            ['name' => 'edit payment'],
            ['name' => 'delete payment'],
            ['name' => 'delete invoice product'],
            ['name' => 'delete bill product'],
            ['name' => 'send invoice'],
            ['name' => 'create payment invoice'],
            ['name' => 'delete payment invoice'],
            ['name' => 'send bill'],
            ['name' => 'create payment bill'],
            ['name' => 'delete payment bill'],
            ['name' => 'income report'],
            ['name' => 'expense report'],
            ['name' => 'income vs expense report'],
            ['name' => 'invoice report'],
            ['name' => 'bill report'],
            ['name' => 'stock report'],
            ['name' => 'tax report'],
            ['name' => 'loss & profit report'],
            ['name' => 'manage transaction'],
            ['name' => 'manage order'],
            ['name' => 'manage credit note'],
            ['name' => 'create credit note'],
            ['name' => 'edit credit note'],
            ['name' => 'delete credit note'],
            ['name' => 'manage debit note'],
            ['name' => 'create debit note'],
            ['name' => 'edit debit note'],
            ['name' => 'delete debit note'],
            ['name' => 'duplicate invoice'],
            ['name' => 'convert invoice'],
            ['name' => 'duplicate bill'],
            ['name' => 'manage proposal'],
            ['name' => 'create proposal'],
            ['name' => 'edit proposal'],
            ['name' => 'delete proposal'],
            ['name' => 'duplicate proposal'],
            ['name' => 'show proposal'],
            ['name' => 'send proposal'],
            ['name' => 'delete proposal product'],
            ['name' => 'manage goal'],
            ['name' => 'create goal'],
            ['name' => 'edit goal'],
            ['name' => 'delete goal'],
            ['name' => 'manage assets'],
            ['name' => 'create assets'],
            ['name' => 'edit assets'],
            ['name' => 'delete assets'],
            ['name' => 'statement report'],
            ['name' => 'manage constant custom field'],
            ['name' => 'create constant custom field'],
            ['name' => 'edit constant custom field'],
            ['name' => 'delete constant custom field'],
            ['name' => 'manage chart of account'],
            ['name' => 'create chart of account'],
            ['name' => 'edit chart of account'],
            ['name' => 'delete chart of account'],
            ['name' => 'manage journal entry'],
            ['name' => 'create journal entry'],
            ['name' => 'edit journal entry'],
            ['name' => 'delete journal entry'],
            ['name' => 'show journal entry'],
            ['name' => 'balance sheet report'],
            ['name' => 'ledger report'],
            ['name' => 'trial balance report'],
            ['name' => 'manage budget planner'],
            ['name' => 'create budget planner'],
            ['name' => 'edit budget planner'],
            ['name' => 'delete budget planner'],
            ['name' => 'view budget planner'],
            ['name' => 'manage contract'],
            ['name' => 'create contract'],
            ['name' => 'edit contract'],
            ['name' => 'delete contract'],
            ['name' => 'view contract'],
            ['name' => 'duplicate contract'],
            ['name' => 'delete attachment'],
            ['name' => 'delete comment'],
            ['name' => 'delete notes'],
            ['name' => 'contract description'],
            ['name' => 'upload attachment'],
            ['name' => 'add comment'],
            ['name' => 'add notes'],
            ['name' => 'send contract mail'],
            ['name' => 'manage retainer'],

            
            
        ];

        $companyRole->givePermissionTo($companyPermissions);

        $company = User::create(
            [
                'name' => 'company',
                'email' => 'company@example.com',
                'password' => Hash::make('1234'),
                'type' => 'company',
                'lang' => 'en',
                'avatar' => '',
                'plan' => 1,
                'created_by' => $superAdmin->id,
            ]
        );
        $company->assignRole($companyRole);

        // accountant
        $accountantRole = Role::create(
            [
                'name' => 'accountant',
                'created_by' => $company->id,
            ]
        );

        $accountantPermission = [
            ['name' => 'show dashboard'],
            ['name' => 'manage expense'],
            ['name' => 'create expense'],
            ['name' => 'edit expense'],
            ['name' => 'delete expense'],
            ['name' => 'manage invoice'],
            ['name' => 'create invoice'],
            ['name' => 'edit invoice'],
            ['name' => 'delete invoice'],
            ['name' => 'show invoice'],
            ['name' => 'convert invoice'],
            ['name' => 'manage product & service'],
            ['name' => 'create product & service'],
            ['name' => 'delete product & service'],
            ['name' => 'edit product & service'],
            ['name' => 'manage constant tax'],
            ['name' => 'create constant tax'],
            ['name' => 'edit constant tax'],
            ['name' => 'delete constant tax'],
            ['name' => 'manage constant category'],
            ['name' => 'create constant category'],
            ['name' => 'edit constant category'],
            ['name' => 'delete constant category'],
            ['name' => 'manage constant unit'],
            ['name' => 'create constant unit'],
            ['name' => 'edit constant unit'],
            ['name' => 'delete constant unit'],
            ['name' => 'manage customer'],
            ['name' => 'create customer'],
            ['name' => 'edit customer'],
            ['name' => 'delete customer'],
            ['name' => 'show customer'],
            ['name' => 'manage vender'],
            ['name' => 'create vender'],
            ['name' => 'edit vender'],
            ['name' => 'delete vender'],
            ['name' => 'show vender'],
            ['name' => 'manage bank account'],
            ['name' => 'create bank account'],
            ['name' => 'edit bank account'],
            ['name' => 'delete bank account'],
            ['name' => 'manage transfer'],
            ['name' => 'create transfer'],
            ['name' => 'edit transfer'],
            ['name' => 'delete transfer'],
            ['name' => 'manage revenue'],
            ['name' => 'create revenue'],
            ['name' => 'edit revenue'],
            ['name' => 'delete revenue'],
            ['name' => 'manage bill'],
            ['name' => 'create bill'],
            ['name' => 'edit bill'],
            ['name' => 'delete bill'],
            ['name' => 'show bill'],
            ['name' => 'manage payment'],
            ['name' => 'create payment'],
            ['name' => 'edit payment'],
            ['name' => 'delete payment'],
            ['name' => 'delete invoice product'],
            ['name' => 'delete bill product'],
            ['name' => 'send invoice'],
            ['name' => 'create payment invoice'],
            ['name' => 'delete payment invoice'],
            ['name' => 'send bill'],
            ['name' => 'create payment bill'],
            ['name' => 'delete payment bill'],
            ['name' => 'income report'],
            ['name' => 'expense report'],
            ['name' => 'income vs expense report'],
            ['name' => 'invoice report'],
            ['name' => 'bill report'],
            ['name' => 'stock report'],
            ['name' => 'tax report'],
            ['name' => 'loss & profit report'],
            ['name' => 'manage transaction'],
            ['name' => 'manage credit note'],
            ['name' => 'create credit note'],
            ['name' => 'edit credit note'],
            ['name' => 'delete credit note'],
            ['name' => 'manage debit note'],
            ['name' => 'create debit note'],
            ['name' => 'edit debit note'],
            ['name' => 'delete debit note'],
            ['name' => 'manage proposal'],
            ['name' => 'create proposal'],
            ['name' => 'edit proposal'],
            ['name' => 'delete proposal'],
            ['name' => 'duplicate proposal'],
            ['name' => 'send proposal'],
            ['name' => 'show proposal'],
            ['name' => 'delete proposal product'],
            ['name' => 'manage goal'],
            ['name' => 'create goal'],
            ['name' => 'edit goal'],
            ['name' => 'delete goal'],
            ['name' => 'manage assets'],
            ['name' => 'create assets'],
            ['name' => 'edit assets'],
            ['name' => 'delete assets'],
            ['name' => 'statement report'],
            ['name' => 'manage constant custom field'],
            ['name' => 'create constant custom field'],
            ['name' => 'edit constant custom field'],
            ['name' => 'delete constant custom field'],
            ['name' => 'manage chart of account'],
            ['name' => 'create chart of account'],
            ['name' => 'edit chart of account'],
            ['name' => 'delete chart of account'],
            ['name' => 'manage journal entry'],
            ['name' => 'create journal entry'],
            ['name' => 'edit journal entry'],
            ['name' => 'delete journal entry'],
            ['name' => 'show journal entry'],
            ['name' => 'balance sheet report'],
            ['name' => 'ledger report'],
            ['name' => 'trial balance report'],
            ['name' => 'manage budget planner'],
            ['name' => 'create budget planner'],
            ['name' => 'edit budget planner'],
            ['name' => 'delete budget planner'],
            ['name' => 'view budget planner'],
            ['name' => 'manage retainer'],

        ];

        $accountantRole->givePermissionTo($accountantPermission);

        $accountant = User::create(
            [
                'name' => 'accountant',
                'email' => 'accountant@example.com',
                'password' => Hash::make('1234'),
                'type' => 'accountant',
                'lang' => 'en',
                'avatar' => '',
                'created_by' => $company->id,
            ]
        );
        $accountant->assignRole($accountantRole);

        \App\Models\BankAccount::create(
            [
                'holder_name' => 'Cash',
                'bank_name' => '',
                'account_number' => '-',
                'opening_balance' => '0.00',
                'contact_number' => '-',
                'bank_address' => '-',
                'created_by' => $company->id,
            ]
        );

        Utility::chartOfAccountTypeData();
        Utility::chartOfAccountData($company);
        $company->defaultEmail();
        $company->userDefaultData();
        
    }
}
